adapter: lora
bf16: true
chat_template: llama3
data_processes: 16
dataset_prepared_path:
datasets:
debug:
deepspeed:
do_eval: true
early_stopping_patience: 5
eval_batch_size: 4
eval_max_new_tokens: 128
eval_steps: 50
eval_table_size:
evals_per_epoch:
flash_attention: true
fp16: false
fsdp:
fsdp_config:
gradient_accumulation_steps: 2
gradient_checkpointing: true
group_by_length: true
hub_model_id:
hub_repo:
hub_strategy: checkpoint
hub_token:
learning_rate: 0.0001018
load_in_4bit: false
load_in_8bit: false
local_rank:
logging_steps: 1
lora_alpha: 128
lora_dropout: 0.05
lora_fan_in_fan_out:
lora_model_dir:
lora_r: 64
lora_target_linear: true
lr_scheduler: linear
max_grad_norm: 1.0
max_steps: 200
micro_batch_size: 4
mlflow_experiment_name:
model_type: AutoModelForCausalLM
num_epochs: 3
optim_args:
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_epsilon: 1e-5
optimizer: adamw_bnb_8bit
output_dir: miner_id_24
pad_to_sequence_len: true
resume_from_checkpoint:
s2_attention:
sample_packing: false
save_steps: 50
saves_per_epoch:
sequence_len: 1024
strict: false
tf32: true
tokenizer_type: AutoTokenizer
train_on_inputs: false
trust_remote_code: true
val_set_size: 0.05
wandb_entity:
wandb_mode: online
wandb_name:
wandb_project: ab-god18
wandb_run: your_name
wandb_runid: default
warmup_steps: 10
weight_decay: 0.0
xformers_attention:
